version: '3.9'

services:
  db:
    image: mariadb:10.11
    volumes:
    - db:/var/lib/mysql
    restart: unless-stopped
    ports:
      - "3306:3306"
    environment:
      MARIADB_ROOT_PASSWORD: lunit
      MARIADB_DATABASE: lunitexam
      MARIADB_USER: lunit
      MARIADB_PASSWORD: lunit
    networks:
    - lunitn

  lunit:
    build:
      context: .
      dockerfile: Dockerfile
    image: lunit:latest
    volumes:
      - lunit:/app/download
    depends_on:
    - db
    ports:
    - "8280:8280"
    restart: unless-stopped
    environment:
      LUNIT_DB_HOST: db:3306
      LUNIT_DB_USER: lunit
      LUNIT_DB_PASSWORD: lunit
      LUNIT_DB_DOWNLOAD: /app/download
      LUNIT_SERVER_PORT: 8280
    networks:
    - lunitn

volumes:
  db: {}
  lunit: {}

networks:
  lunitn: {}