
spring:
  # mariaDB
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
#    url: jdbc:mariadb://172.19.148.92:3306/lunitexam
    url: jdbc:mariadb://${LUNIT_DB_HOST:172.19.148.92:3306}/lunitexam?useSSL=false&useUnicode=true&serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: ${LUNIT_DB_USER:root}
    password: ${LUNIT_DB_PASSWORD:shin6182!}
    hikari:
      data-source-properties:
        characterEncoding: UTF-8
        useUnicode: true
      maximum-pool-size: ${MYSQL_MAX_POOL_SIZE:20}
      register-mbeans: true
      pool-name: hikari
  ########################### jpa 설정 ################################
  jpa:
    defer-datasource-initialization: true
    generate-ddl: true
    show-sql: true
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        format_sql: true
        jdbc:
          time_zone: Asia/Seoul
#MultiPart
  servlet:
    multipart.max-file-size: 100GB
    multipart.max-request-size: 100GB
    multipart.location: ${LUNIT_DB_DOWNLOAD:/Users/shc78/temp}
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    operations-sorter: alpha
    tags-sorter: alpha
    path: /swagger-ui.html
    disable-swagger-default-url: true

###### cusmtom setting #####
slice:
  min: 17
  max: 50